
    TWITTER_CONSUMER_KEY = ENV["TWITTER_CONSUMER_KEY"]
    TWITTER_CONSUMER_SECRET = ENV["TWITTER_CONSUMER_SECRET"]
    FACEBOOK_APP_ID = ENV["FACEBOOK_APP_ID"]
    FACEBOOK_APP_SECRET = ENV["FACEBOOK_APP_SECRET"]
    # GITHUB_CLIENT_ID = ENV["GITHUB_CLIENT_ID"]
    # GITHUB_SECRET = ENV["GITHUB_SECRET"]
    
